plugins {
    id 'maven-publish'
    id 'com.enonic.defaults' version '2.1.7'
    id 'com.enonic.xp.app'
}

repositories {
    mavenLocal()
    mavenCentral()
    xp.enonicRepo('dev')
}

dependencies {
    include xplibs.content
    include xplibs.context
    include xplibs.portal
    include xplibs.auth
    include xplibs.project
    include xplibs.cluster
    include xplibs.export
    include xplibs.i18n
    include xplibs.node
    include xplibs.repo
    include xplibs.task
    include libs.lib.thymeleaf
    include libs.lib.xslt
    include libs.lib.asset

    testImplementation "com.enonic.xp:testing:${xpVersion}"
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:6.1.3'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:6.1.3'
}

test {
    useJUnitPlatform()
}

xp {
    scriptEngines = ['Nashorn', 'GraalJS']
}
